<?php

/**
 * BaseDoctor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $apellido
 * @property string $especialidad
 * @property string $telefono
 * @property string $email
 * @property Doctrine_Collection $Citas
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getApellido()     Returns the current record's "apellido" value
 * @method string              getEspecialidad() Returns the current record's "especialidad" value
 * @method string              getTelefono()     Returns the current record's "telefono" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method Doctrine_Collection getCitas()        Returns the current record's "Citas" collection
 * @method Doctor              setNombre()       Sets the current record's "nombre" value
 * @method Doctor              setApellido()     Sets the current record's "apellido" value
 * @method Doctor              setEspecialidad() Sets the current record's "especialidad" value
 * @method Doctor              setTelefono()     Sets the current record's "telefono" value
 * @method Doctor              setEmail()        Sets the current record's "email" value
 * @method Doctor              setCitas()        Sets the current record's "Citas" collection
 * 
 * @package    reto_symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDoctor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doctor');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('especialidad', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cita as Citas', array(
             'local' => 'id',
             'foreign' => 'doctor_id'));
    }
}