<?php

/**
 * BasePaciente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $apellido
 * @property string $documento
 * @property string $telefono
 * @property string $email
 * @property date $fecha_nacimiento
 * @property Doctrine_Collection $Citas
 * 
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getApellido()         Returns the current record's "apellido" value
 * @method string              getDocumento()        Returns the current record's "documento" value
 * @method string              getTelefono()         Returns the current record's "telefono" value
 * @method string              getEmail()            Returns the current record's "email" value
 * @method date                getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method Doctrine_Collection getCitas()            Returns the current record's "Citas" collection
 * @method Paciente            setNombre()           Sets the current record's "nombre" value
 * @method Paciente            setApellido()         Sets the current record's "apellido" value
 * @method Paciente            setDocumento()        Sets the current record's "documento" value
 * @method Paciente            setTelefono()         Sets the current record's "telefono" value
 * @method Paciente            setEmail()            Sets the current record's "email" value
 * @method Paciente            setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Paciente            setCitas()            Sets the current record's "Citas" collection
 * 
 * @package    reto_symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaciente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('documento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cita as Citas', array(
             'local' => 'id',
             'foreign' => 'paciente_id'));
    }
}